spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:./back_end/database/photoClassification.db
  servlet:
    multipart:
      max-file-size: 10MB  # 单个文件的最大上传大小
      max-request-size: 10MB  # 总的最大请求大小
  sql:
    init:
      mode: always
  web:
    resources:
      static-locations: file:ImagesArchivedByDate/
  config:
    import: "classpath:config.properties"
server:
  port: 8888
mybatis:
  configuration:
    map-underscore-to-camel-case: true #开启驼峰命名和下划线命名替换
